
server:
  port: 18081

spring:
  datasource:
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/application_db
      username: forlks
      password: forlks
      poolName: PostgreSQL-Pool
      maxPoolSize: 5
      leakDetectionThreshold: 30000
  rabbitmq:
    host: localhost
    port: 5672
    username: forlks
    password: forlks
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

ks:
  rabbitmq:
    exchange:
      works-queue: forlks.make.coffee
      round-robin: forlks.make.coffees
    queue:
      works-queue: forlks.make.coffee.queue
      round-robin: forlks.make.coffees.queue
